create table users
(
    id       bigint generated by default as identity
        primary key,
    login    varchar(100) not null
        constraint ukow0gan20590jrb00upg3va2fn
            unique,
    password varchar(150) not null
);