create table locations
(
    id        bigint generated by default as identity
        primary key,
    latitude  double precision not null,
    longitude double precision not null,
    name      varchar(30),
    user_id   bigint           not null
);
ALTER TABLE IF EXISTS locations
    ADD CONSTRAINT FKdmtxqhxbtg4qt8q6u01hxj52i
    FOREIGN KEY (user_id)
    REFERENCES users(id);